#https://www.mydailytutorials.com/ansible-add-line-to-file/
#https://stackoverflow.com/questions/38078247/how-to-create-ansible-playbook-to-obtain-os-versions-of-the-remote-hosts/51255585

- name: "Gather OS Data"
  package_facts:
   manager: auto

- name: "OS Data Recorded Before Any OS Changes"
  lineinfile:                                                                 ##  Specify path
    path: /etc/ansible/OSData/PlaybookDeployed@{{ OriginalOSTimeStamp.stdout }}/OSData@-{{ OriginalOSTimeStamp.stdout }}.csv
    mode: 0644                                                                ##  File permissions
                                                                              ##  Data variables from Telent's servers to be Logged - note the AFTER.
    line: "{{ ansible_hostname }},\
                  {{ ansible_distribution }},\
                  {{ ansible_distribution_version }},\
                  {{ ansible_distribution_release }},\
                  {{ OriginalOSTimeStamp.stdout }},\
                  BEFORE"                                                     ##  Data to be recorded - Note the "Before"
    create: yes ## create if not existing
  delegate_to: localhost ## Prevents issues regarding Python interpreters
