- name: "OS Data Recorded Before Changes"
  lineinfile:
    path: /etc/ansible/OSData/PlaybookDeployed@{{ OriginalOSTimeStamp.stdout }}/OSData@-{{ OriginalOSTimeStamp.stdout }}.csv
    mode: 0644
    line: "{{ ansible_hostname }},\
                  {{ ansible_distribution }},\
                  {{ ansible_distribution_version }},\
                  {{ ansible_distribution_release }},\
                  {{ OriginalOSTimeStamp.stdout }},\
                  AFTER"
    create: yes
  delegate_to: localhost
