galaxy_info:
  author: Ciaran Morrow
  description: Design Engineer
  company: Telent Technology Services

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []
