---
- name: Add Users Playbook
  become: true
  hosts: CentosBoxes
  gather_facts: true
  vars_files:
    - /etc/ansible/Roles/UsersProject/vars/UserVarsFile.yml
  tasks:
    ###https://stackoverflow.com/questions/58113653/using-ansible-loop-to-create-multiple-users-undefined-error
    ## https://docs.ansible.com/ansible/latest/collections/ansible/builtin/items_lookup.html

        - name: Adding to CentosBoxes Using Variables in UserVarsFile.yml
          user:
            name: "{{ item.New_User_Name }}"
            shell: /bin/bash
            comment: "{{ item.New_User_Comment }}"
            uid: "{{ item.New_User_UID }}"
            state: present
           #groups: "{{ item.groups }}"
          with_items: "{{ authorised_user }}"



        - name: Adding Authorised Key to New User
          authorized_key:
            user: "{{ item.New_User_Name }}"
            exclusive: false
            state: present
            key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
          with_items: "{{ authorised_user }}"
