---
Auth_Usr_Telent:                                                                ##  List of variables
  -
    Telent_User_Comment: New User Ciaran Added                                  ##  User comment
    Telent_UserName: Ciaran                                                     ##  Username variable
    Telent_User_ID: 100
    Telent_Sudoer: true                                                          ##  User identification
  -
    Telent_User_Comment: New User Daniel Added                                  ##  User comment
    Telent_UserName: Daniel                                                     ##  Username variable
    Telent_User_ID: 123
    Telent_Sudoer: false                                                        ##  User identification
  -
    Telent_User_Comment: New User James Added                                   ##  User comment
    Telent_UserName: Shaun                                                      ##  Username variable
    Telent_User_ID: 123423
    Telent_Sudoer: true                                                       ##  User identification


Unauth_Usr_Telent:                                                              ##  List of variables
  -
    Telent_Unauth_User: Ciaran                                                  ##  Username variable
  -
    Telent_Unauth_User: Ciaranm                                                 ##  Username variable
