---
- name: Adding to Targets Using Variables in Main.yml
  user:
     name: "{{ item.Telent_UserName }}"                                         ##  Using username as Var to enable multiple users to be added - better maintainablity
     shell: /bin/bash                                                         ##  Permitted
     comment: "{{ item.Telent_User_Comment }}"                                   ##  Adding Comment for each user - see vars
  #   uid: "{{ item.Telent_User_ID }}"                                          ##  Assigning user ID if necessary
     state: present                                                           ##  User present // could be absent
  with_items: "{{ Auth_Usr_Telent }}"                                         ##  Using list located in variables
