##  https://www.linode.com/docs/guides/modify-file-permissions-with-chmod/
##  https://docs.ansible.com/ansible/latest/collections/ansible/builtin/fetch_module.html
##  https://docs.ansible.com/ansible/2.3/playbooks_roles.html


- name: Get a timestamp
  command: date +%M%H%d%m%Y                                                   ##  Minutes, Hour, Day, Month, Year
  register: timestamp                                                         ##  Timestamp variable -

- name: Creating Deployment Folder
  file:
    state: directory                                                          ##  Creating deployment folder
    path: /etc/PASSWORD/{{ inventory_hostname }}/{{ inventory_hostname }}-{{ timestamp.stdout }} ## Using variables with path file
    mode: u+rw,g-wx,o-rwx                                                     ##  File permissions

- name: Download list of users file from Remote Machine #to Local ansible node without directory structures
  fetch:
    src: /etc/passwd                                                          ##  Retrieving documents
    dest: /etc/PASSWORD/{{ inventory_hostname }}/Passwd-{{ inventory_hostname }}-{{ timestamp.stdout }}  ## Destination to download list to
    flat: yes                                                                 ##  Flat file directory
