authorised_user:
  -   New_User_Name: Ciaran
      New_User_UID: 10
      New_User_Comment: 223333

  -   New_User_Name: Ciaranm
      New_User_UID: 100233
      New_User_Comment: 22233

  -   New_User_Name: Ibrahim23
      New_User_UID: 1234
      New_User_Comment: 1212

unauthorised_users:
  -   name: Ciaran
  -   name: Ciaranm
